# Generated by Django 4.0.4 on 2022-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brandtype_car_fueltype_location_tranmissiontype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuel',
            new_name='fuel_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='transmission',
            new_name='transmission_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='reservation',
            new_name='reservation_id',
        ),
    ]
