# Generated by Django 4.0.4 on 2022-05-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_brand_car_brand_id_rename_fuel_car_fuel_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
    ]
