# Generated by Django 4.0.4 on 2022-05-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_id_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmission_id',
            new_name='transmission_type',
        ),
    ]
