# Generated by Django 4.0.4 on 2022-05-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_brand_id_car_brand_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranmissionType',
            new_name='TransmissionType',
        ),
    ]
