# Generated by Django 4.0.4 on 2022-05-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_tranmissiontype_transmissiontype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='pickup_location_id',
            new_name='pickup_location',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='return_location_id',
            new_name='return_location',
        ),
    ]
