# Generated by Django 4.0.4 on 2022-05-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_car_brand_type_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.location'),
            preserve_default=False,
        ),
    ]
