# Generated by Django 4.0.4 on 2022-05-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_car_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_active',
            new_name='is_allocated',
        ),
    ]
