# Generated by Django 4.0.4 on 2022-05-30 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_is_active_car_is_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_allocated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
