# Generated by Django 4.0.4 on 2022-05-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_car_is_allocated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_allocated',
            new_name='allocated_by',
        ),
    ]
