# Generated by Django 4.0.4 on 2022-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_car_allocated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
