# Generated by Django 4.0.4 on 2022-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('personalID', models.CharField(max_length=40)),
            ],
        ),
    ]
